# Profile AWS - As credenciais e endpoint do RDS são buscados via AWS Secrets Manager
# O Spring Cloud AWS injeta automaticamente as propriedades do path configurado.

spring:
  config:
    import:
      - "aws-secretsmanager:secret-sgl-db-credentials-v1"

  datasource:
    url: jdbc:postgresql://${host}:${port}/sgl_tenant_db
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver

  cloud:
    aws:
      region:
        static: us-east-2
      secretsmanager:
        region: us-east-2
      parameterstore:
        enabled: false

  jpa:
    show-sql: false

  flyway:
    enabled: true

logging:
  level:
    com.sgl.tenant: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN